### PR TITLE
feature: Adding log retention

### PR DESCRIPTION
**Pull request by edogden-pbx**
The following feature change adds log retention to the Lambda functions LogGroup.
This should help reduce the amount of Lambda logs stored in AWS which will cut down on CloudWatch log storage costs.

In this propose I have defaulted to 90 days as a good baseline, however we might want to reduce this further.

As found per my previous PR https://github.com/dynatrace-oss/dynatrace-aws-log-forwarder/pull/50 this is set in the run script to support the updating of the stack.

### CODE REVIEW

**Comment by dt-be** [comment]
Seems a reasonable thing to add. 
I'd much rather see it as a part of cloudformation than as a separate call though - there are a lot of things configured there already and I would keep it all there. Something like below maybe, I think it would also work on updating the stack, but please check.

dynatrace-aws-log-forwarder-template.yaml
```
  Lambda:
     ...

  LambdaSelfMonitoringLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Lambda}"
      RetentionInDays: 90
      
  LambdaRole:
    ...
```
      
90 might even be too much, but unless anyone else protests, let's have it for a start.

**Comment by mmajcher** [comment]
Seems good 👍 
I would probably give max 30 days, what do you think?
Otherwise looks good.

Our intention for Contributing is to have external fork merged to a feature branch (not master), we will update you how to proceed.
Because our tests do not run from external fork for security reasons so you will not pass checks. We need to organise this somehow :)

**Review by wojtasskorcz — APPROVED** [review]

**Comment by edogden-pbx** [comment]
> Seems good 👍 I would probably give max 30 days, what do you think? Otherwise looks good.
> 
> Our intention for Contributing is to have external fork merged to a feature branch (not master), we will update you how to proceed. Because our tests do not run from external fork for security reasons so you will not pass checks. We need to organise this somehow :)

let me know if you need me to do anything

**Comment by dt-be** [comment]
Hi. 
I've created a target branch for you to merge into, and updated it in the PR.
Please merge current dynatrace-oss/master into your branch, it should be able to merge after that.

**Review by kamiljsokolowski — APPROVED** [review]

**Pull request merged**
